/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oftSol from "./OFT.sol";
export type { oftSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { StableWrapper } from "./StableWrapper";
export type { StreamVault } from "./StreamVault";
export type { TestToken } from "./TestToken";
