/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IStableWrapper__factory } from "./IStableWrapper__factory";
export { IWETH__factory } from "./IWETH__factory";
